import Distribution.Simple
main = defaultMain
# Stack build artifacts
.stack-work/
.stack-work-install/

# Cabal file generated by hpack (from package.yaml)
simple.cabal

# Local binary installs
dist/
dist-newstyle/
*.hi
*.o

# Stack install binaries
~/.local/bin/*

# GHC environment and config files
.ghc.environment.*
ghc.environment.*

# Vim/Emacs/VSCode/JetBrains/etc.
*.swp
*.swo
*.bak
*.tmp
*~

# macOS metadata
.DS_Store

# VSCode settings (optional, if you want a clean repo)
.vscode/

# Stack lockfile (optional, comment if you want reproducible builds)
stack.yaml.lock

# Env files (if they contain secrets)
.env
.env.*