version: "3.9"

services:
  postgres:
    image: postgres:14
    container_name: ${CONTAINER_NAME}
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./backups:/backups
    env_file:
      - .env

volumes:
  pgdata: