on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Haskell with Stack
        uses: haskell/actions/setup@v2
        with:
          enable-stack: true
          stack-version: 'latest'

      - name: Restore stack.yaml
        run: |
          if [ ! -f stack.yaml ]; then
            echo 'resolver: lts-23.24' > stack.yaml
          fi

      - name: Disable Haddock docs
        run: |
          grep -q '^build:' stack.yaml || echo "build:\n  haddock: false" >> stack.yaml

      - name: Install dependencies
        run: stack setup && stack build --only-dependencies

      - name: Build
        run: stack build

      - name: Run tests
        run: |
          if grep -q 'tests:' package.yaml || grep -qr test/ .; then
            stack test
          else
            echo "No tests defined, skipping."
          fi
