on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Haskell (Stack)
        uses: haskell/actions/setup@v2
        with:
          enable-stack: true
          stack-version: 'latest'

      - name: Pin snapshot manually
        run: "echo 'resolver: lts-23.24' > stack.yaml"

      - name: Disable Haddock docs
        run: |
          echo "build:" >> stack.yaml
          echo "  haddock: false" >> stack.yaml

      - name: Install dependencies
        run: stack setup && stack build --only-dependencies

      - name: Build
        run: stack build

      - name: Run tests
        run: stack test