name: Haskell CI (Stack)

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Haskell (Stack)
        uses: haskell/actions/setup@v2
        with:
          enable-stack: true
          stack-version: 'latest'

      - name: Configure Stack to disable Haddock fetch
        run: |
            echo "build:" >> stack.yaml
            echo "  haddock: false" >> stack.yaml

      - name: Install dependencies
        run: stack setup && stack build --only-dependencies

      - name: Build
        run: stack build

      - name: Run tests
        run: stack test